### ISSUE TITLE
No implementation found for long me.weishu.epic.art.EpicNative.getMethodAddress(java.lang.reflect.Member)

### ISSUE THREAD

**Issue by qzcsfchh** [huage2580/PermissionMonitor#1]
========================================crash info==========================================

2021-08-16 23:21:15.845 27650-27650/com.hua.testhook E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hua.testhook, PID: 27650
    java.lang.UnsatisfiedLinkError: No implementation found for long me.weishu.epic.art.EpicNative.getMethodAddress(java.lang.reflect.Member) (tried Java_me_weishu_epic_art_EpicNative_getMethodAddress and Java_me_weishu_epic_art_EpicNative_getMethodAddress__Ljava_lang_reflect_Member_2)
        at me.weishu.epic.art.EpicNative.getMethodAddress(Native Method)
        at me.weishu.epic.art.method.ArtMethod.init(ArtMethod.java:93)
        at me.weishu.epic.art.method.ArtMethod.<init>(ArtMethod.java:86)
        at me.weishu.epic.art.method.ArtMethod.of(ArtMethod.java:98)
        at me.weishu.epic.art.Epic.hookMethod(Epic.java:79)
        at de.robv.android.xposed.DexposedBridge.hookMethod(DexposedBridge.java:122)
        at de.robv.android.xposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:176)
        at com.hua.permissionmonitor.PermissionMonitor.registerMethod(PermissionMonitor.java:65)
        at com.hua.permissionmonitor.PermissionMonitor.hookMethod(PermissionMonitor.java:75)
        at com.hua.permissionmonitor.PermissionMonitor.start(PermissionMonitor.java:50)
        at com.hua.testhook.MainActivity.onCreate(MainActivity.kt:19)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by liyujiang-gzu** [comment]
#2 

xposed没下载下来，加上这个依赖：
```groovy
implementation 'me.weishu:epic:1.0.0'
```
